# fly.toml app configuration file generated for rvu-dash on 2023-06-15T09:06:22-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rvu-dash"
primary_region = "sea"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8501"

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
